<a href="https://colab.research.google.com/github/aliimronf2/turnupyourpytorch/blob/main/p01_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Start")

Start


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


Import `torch` etc.

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


**Introduction to Tensors**

Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as Python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

Penjelasan `shape`
![Penjelasan dim](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

Random tensors

In [17]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2877, 0.0071, 0.6434, 0.9499],
        [0.1380, 0.1006, 0.6968, 0.6412],
        [0.2254, 0.4578, 0.1525, 0.4982]])

In [18]:
random_tensor.ndim

2

In [19]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeros and ones

In [20]:
# create a tensor of all zeros
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# create a tensor of all ones
one = torch.ones(size=(3, 4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
one.dtype

torch.float32

**Creating a range of tensors and tensors-like**

In [23]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
odd_one_to_fifteen = torch.arange(start=1, end=15, step=2)
odd_one_to_fifteen

tensor([ 1,  3,  5,  7,  9, 11, 13])

In [25]:
# creating tensor-like
odds = torch.zeros_like(odd_one_to_fifteen)
odds

tensor([0, 0, 0, 0, 0, 0, 0])

**Tensor data types**

In [26]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor.dtype

torch.float16

Creating a tensor with the most important parameters: `dtype`, `device`, `requires_grad`.

In [30]:
float_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None,
                            device=None, # e.g "cpu", "cuda"
                            requires_grad=False) # whether or not to track gradients with the tensor operations
float_tensor

tensor([3., 6., 9.])

In [31]:
# change data type
float_16_tensor_again = float_32_tensor.type(torch.float16)
float_16_tensor_again

tensor([3., 6., 9.], dtype=torch.float16)

Operations with tensors

In [32]:
f32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
i32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

f32_tensor * i32_tensor

tensor([ 9., 36., 81.])

In [33]:
tensor1 =  torch.rand(3, 4)
tensor1

tensor([[0.3444, 0.8565, 0.7866, 0.2206],
        [0.3104, 0.0928, 0.4421, 0.6544],
        [0.8628, 0.3239, 0.7510, 0.5151]])

In [34]:
print(tensor1)
print(f"Dataype of tensor: {tensor1.dtype}")
print(f"Shape of tensor: {tensor1.shape}")
print(f"Device tensor is on: {tensor1.device}")

tensor([[0.3444, 0.8565, 0.7866, 0.2206],
        [0.3104, 0.0928, 0.4421, 0.6544],
        [0.8628, 0.3239, 0.7510, 0.5151]])
Dataype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


**Manipulating Tensor**

Tensor operations include
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [35]:
tensor_a = torch.tensor([1, 2, 3])
tensor_a + 10

tensor([11, 12, 13])

In [36]:
tensor_a * 5

tensor([ 5, 10, 15])

In [37]:
tensor_a - 10

tensor([-9, -8, -7])

In [38]:
# torch built-in functions
torch.mul(tensor_a, 10)

tensor([10, 20, 30])

In [39]:
tensor_a * tensor_a

tensor([1, 4, 9])

In [40]:
# matrix multiplication
torch.matmul(tensor_a, tensor_a)

tensor(14)

In [41]:
%%time
value = 0
for i in range(len(tensor_a)):
  value += tensor_a[i] * tensor_a[i]

print(value)

tensor(14)
CPU times: user 1.16 ms, sys: 0 ns, total: 1.16 ms
Wall time: 3.15 ms


In [42]:
%%time

torch.matmul(tensor_a, tensor_a)

CPU times: user 105 µs, sys: 15 µs, total: 120 µs
Wall time: 125 µs


tensor(14)

In [43]:
tensor_b = torch.tensor([[1, 4],
                         [5, 8]])
tensor_b

tensor([[1, 4],
        [5, 8]])

In [44]:
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 2x2)

In [45]:
tensor_c = torch.tensor([[1, 4],
                         [5, 8],
                         [0, 9]])
tensor_c

tensor([[1, 4],
        [5, 8],
        [0, 9]])

In [46]:
torch.matmul(tensor_a, tensor_c)

tensor([11, 47])

In [47]:
tensor_d = torch.tensor([[1, 3],
                        [2, 9]])
tensor_d

tensor([[1, 3],
        [2, 9]])

In [48]:
torch.matmul(tensor_c.T, tensor_d)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x2)

In [51]:
torch.matmul(tensor_c, tensor_d)

tensor([[ 9, 39],
        [21, 87],
        [18, 81]])

**Aggregation**

* min
* max
* sum
* mean

In [52]:
tensor_e = torch.arange(0, 100, 10)
tensor_e

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
torch.min(tensor_e), tensor_e.min()

(tensor(0), tensor(0))

In [54]:
tensor_e.max()

tensor(90)

In [55]:
torch.mean(tensor_e.type(torch.float32))

tensor(45.)

In [56]:
tensor_e.type(torch.float32).mean()

tensor(45.)

In [57]:
tensor_e.sum()

tensor(450)

In [58]:
tensor_e = tensor_e + 1
tensor_e

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [59]:
# Find the position of min value
tensor_e.argmin()

tensor(0)

In [60]:
# Find the position of max value
tensor_e.argmax()

tensor(9)

* Reshaping tensors - reshapes an input tensor to a defined shape
* View - return a view of an input of certain shape but keep the same memory as the original tensor
* Stacking - concatenates a sequence of tensors along a new dimension
* Squeezing - remove all `1` dimensions from a tensor
* Unsqueezing - add a `1` dimenstion to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# Add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [63]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [65]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [67]:
# Squeeze
x_reshaped.shape

torch.Size([3, 3])

In [68]:
x_reshaped.squeeze()

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [69]:
x_reshaped = x_reshaped.reshape(1, 9)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [70]:
# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"Unsqueezed tensor: {x_unsqueezed}")
print(f"Newer shape: {x_unsqueezed.shape}")

Unsqueezed tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Newer shape: torch.Size([1, 9])


In [71]:
# Permute
y = torch.randn(2, 3, 5)
y.size()

torch.Size([2, 3, 5])

In [72]:
yp = torch.permute(y, (2, 0, 1))
yp.size()

torch.Size([5, 2, 3])

In [73]:
y[0, 0, 0], yp[0, 0, 0]

(tensor(0.3344), tensor(0.3344))

**Indexing**

In [74]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
x[0][0]

tensor([1, 2, 3])

In [77]:
x[0][0][2]

tensor(3)

In [78]:
# Slicing
x[0][1:][0:2]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [79]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [80]:
x[:,1:,0:2]

tensor([[[4, 5],
         [7, 8]]])

**pytorch and numpy**

* numpy to pytorch -> `torch.from_numpy(ndarray)`
* pytorch to numpy -> `torch.Tensor.numpy`

In [81]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
array.dtype

dtype('float64')

In [83]:
tensor.dtype

torch.float64

pytorch reflects numpy's default float64 datatypes, unless we override the datatypes

In [84]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
tensor_again = torch.ones(7)
numpy_tensor = tensor_again.numpy()
tensor_again, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [90]:
tensor_again = tensor_again + 1
tensor_again, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility**

Reproducibility is trying to take random out of random

In short, how a neural network learns is start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again ...

To reduce the randomness in neural networks and pytorch, comes the concept of a **random seed**.

Essentially what the random seed does is _flavour_ the randomness.

In [92]:
import torch

# Create two random tensors
rt_a = torch.rand(3,4)
rt_b = torch.rand(3,4)

print(rt_a)
print(rt_b)
print(rt_a == rt_b)

tensor([[0.2699, 0.6725, 0.9236, 0.0323],
        [0.1094, 0.8114, 0.5765, 0.0232],
        [0.0755, 0.9466, 0.0967, 0.6363]])
tensor([[0.3525, 0.2487, 0.9563, 0.1115],
        [0.1355, 0.2086, 0.7942, 0.1511],
        [0.2039, 0.0668, 0.7318, 0.4990]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [93]:
# Make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
