<a href="https://colab.research.google.com/github/aliimronf2/turnupyourpytorch/blob/main/p02_startgpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Thu Jan 15 03:32:25 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Check for GPU access with pytorch

In [2]:
import torch

torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

**Putting tensors (and models) in the GPU**

In [5]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [6]:
# Move tensors to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
# Moving back tensors to CPU
# Since if tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix this
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

**Exercise**

Exercise on [learnpytorch.io](https://www.learnpytorch.io/00_pytorch_fundamentals/)

2. Create a random tensor with shape `(7, 7)`.

In [10]:
# 2. Create a random tensor with shape (7, 7)
import torch

tensor_a = torch.rand(7, 7)
tensor_a

tensor([[0.0324, 0.5688, 0.5393, 0.4804, 0.0029, 0.7651, 0.7834],
        [0.1450, 0.4376, 0.6086, 0.0706, 0.7581, 0.2253, 0.9124],
        [0.4697, 0.9625, 0.6744, 0.7326, 0.6721, 0.5571, 0.2437],
        [0.8222, 0.2492, 0.6236, 0.7696, 0.2978, 0.8589, 0.8059],
        [0.8010, 0.6696, 0.8535, 0.1084, 0.8965, 0.4691, 0.7556],
        [0.6025, 0.6830, 0.6584, 0.2278, 0.5376, 0.4069, 0.0977],
        [0.7100, 0.2304, 0.3900, 0.0750, 0.0156, 0.7987, 0.6040]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
tensor_b = torch.rand(1, 7)
torch.matmul(tensor_a, tensor_b.T)

tensor([[2.1015],
        [2.0230],
        [2.2021],
        [2.5186],
        [2.6010],
        [1.6323],
        [1.7978]])

4. Set the random seed to `0` and do exercises 2 & 3 over again

In [12]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_c = torch.rand(7, 7)
tensor_c

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [13]:
torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(1, 7)
tensor_d

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [14]:
torch.matmul(tensor_c, tensor_d.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.

In [15]:
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [16]:
torch.cuda.manual_seed(1234)
tensor_e = torch.rand(size=[2, 3], device='cuda')
tensor_e

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [17]:
torch.cuda.manual_seed(1234)
tensor_f = torch.rand(size=[2, 3], device='cuda')
tensor_f

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [18]:
torch.matmul(tensor_e, tensor_f.T)

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [19]:
matmul_result = torch.matmul(tensor_e, tensor_f.T)

print(f"The maximum value: {matmul_result.max()}")
print(f"The minimum value: {matmul_result.min()}")

The maximum value: 1.4577524662017822
The minimum value: 0.8358409404754639


9. Find the maximum and minimum index values of the output of 7.

In [20]:
print(f"The maximum value's index: {matmul_result.argmax()}")
print(f"The minimum value's index: {matmul_result.argmin()}")

The maximum value's index: 3
The minimum value's index: 1


10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [21]:
torch.manual_seed(7)
tensor_g = torch.rand(1, 1, 1, 10)
tensor_g, tensor_g.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [22]:
tensor_h = tensor_g.squeeze()
tensor_h, tensor_h.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))